# Generated by Django 2.0.1 on 2018-01-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('q_url', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question_title', models.ForeignKey(db_column='question_title', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quora.Question')),
                ('user_name', models.CharField(max_length=255)),
                ('user_url', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question_title', 'user_name')},
        ),
    ]
