# Generated by Django 2.0.1 on 2018-01-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_auto_20180102_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_title',
            field=models.ForeignKey(db_column='question_title', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quora.Question'),
        ),
    ]
