# Generated by Django 2.0.1 on 2018-01-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_auto_20180102_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quora.Question'),
        ),
    ]
